// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk0FcGPUW2dloExdJN1GA9QX3h5QIXWjc',
    appId: '1:501195478284:web:502c4444067121dbcc6529',
    messagingSenderId: '501195478284',
    projectId: 'car-rental-app-627e7',
    authDomain: 'car-rental-app-627e7.firebaseapp.com',
    storageBucket: 'car-rental-app-627e7.firebasestorage.app',
    measurementId: 'G-0WYE9LNR8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjhctamfU-CzGXRiTLaqZIbeO-fAXvMts',
    appId: '1:501195478284:android:f5afe9eee9df5ec9cc6529',
    messagingSenderId: '501195478284',
    projectId: 'car-rental-app-627e7',
    storageBucket: 'car-rental-app-627e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8jQUo6I2-PAe_7v8AwovQhoYYnnRrpQ',
    appId: '1:501195478284:ios:8d232e0ed9665a37cc6529',
    messagingSenderId: '501195478284',
    projectId: 'car-rental-app-627e7',
    storageBucket: 'car-rental-app-627e7.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe8jQUo6I2-PAe_7v8AwovQhoYYnnRrpQ',
    appId: '1:501195478284:ios:8d232e0ed9665a37cc6529',
    messagingSenderId: '501195478284',
    projectId: 'car-rental-app-627e7',
    storageBucket: 'car-rental-app-627e7.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk0FcGPUW2dloExdJN1GA9QX3h5QIXWjc',
    appId: '1:501195478284:web:e9fef96386b15dfdcc6529',
    messagingSenderId: '501195478284',
    projectId: 'car-rental-app-627e7',
    authDomain: 'car-rental-app-627e7.firebaseapp.com',
    storageBucket: 'car-rental-app-627e7.firebasestorage.app',
    measurementId: 'G-418Z3EEFYG',
  );
}
